# Generated by Django 5.2.7 on 2025-10-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
